eval:
  eval_freq: 10000
  n_eval_episodes: 5
ppo:
  batch_size: 64
  clip_range: 0.2
  ent_coef: 0.01
  gae_lambda: 0.95
  gamma: 0.99
  learning_rate: 0.0003
  n_epochs: 10
  n_steps: 2048
  policy_kwargs:
    net_arch:
      pi:
      - 256
      - 256
      vf:
      - 256
      - 256
training:
  n_envs: 1
  seed: 42
  total_timesteps: 2000000
